CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY NOT NULL,
username TEXT NOT NULL,
password TEXT NOT NULL
);

INSERT INTO users (id,username,password) VALUES ('1','vasco','$2y$10$395b7wODm.o2N7W5UZSXXuXwrC0OtFB17w4VjPnCIn/nvv9e4XUQK');

CREATE TABLE IF NOT EXISTS items (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT,
user_id INTEGER,
done BOOLEAN DEFAULT 0,
created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO items (name,user_id) VALUES ('Clean Room','1');

CREATE UNIQUE INDEX IF NOT EXISTS username ON users (username);
CREATE INDEX IF NOT EXISTS user_id ON items (user_id);

